### ISSUE TITLE
Use OSQP solver for quadratic programming

### ISSUE THREAD

**Issue by rwl** [MATPOWER/mp-opt-model#2]
The University of Oxford has published a QP solver called [OSQP](https://github.com/oxfordcontrol/osqp) that is written in C. The [benchmarks](https://github.com/oxfordcontrol/osqp_benchmarks) show impressive performance relative to some well established solvers. There is an MEX interface for calling the solver from MATLAB:

https://github.com/oxfordcontrol/osqp-matlab

**Comment by rdzman** [comment]
Looks very promising. Thanks. I'll check it out.
